64Qv3:
  control_amplitude:
    # MUX09
    Q36: 0.00001 #0.015442817564889346
    Q37: 0.03765604803900789
    Q38: 0.0610436500381988
    Q39: 0.015251728650066239
    # MUX10
    Q40: 0.01502797296066616
    Q41: 0.08665379329997044
    Q42: 0.22058871674838158
    Q43: 0.0364195114768556

  readout_amplitude:
    # MUX09
    Q36: 0 #0.375
    Q37: 0.2625
    Q38: 0.225
    Q39: 0.3
    # MUX10
    Q40: 0.042
    Q41: 0.042
    Q42: 0.042
    Q43: 0.042

  readout_vatt:
    9: 2048
    10: 2048

  capture_delay:
    9: 0
    10: 6

  capture_delay_word:
    9: 0
    10: 0

  pump_frequency:
    9: 10.25
    10: 10.25
  jpa_params:
    # MUX
    0:
      dc_voltage: 0.1456
      pump_frequency: 10.18
      pump_amplitude: 0.1
    1:
      dc_voltage: 0.344
      pump_frequency: 10.06
      pump_amplitude: 0.1
    2:
      dc_voltage: 0.3725
      pump_frequency: 10.1875
      # pump_amplitude: 0.175
      pump_amplitude: 0.1375
      # dc_voltage: 0.37
      # pump_frequency: 10.166667
      # pump_amplitude: 0.165
    3:
      dc_voltage: 0.4512
      pump_frequency: 10.041667
      pump_amplitude: 0.1188
      # dc_voltage: 0.4158
      # pump_frequency: 10.43
      # pump_amplitude: 0.2
    4:
      dc_voltage: 0.576
      pump_frequency: 10.17
      pump_amplitude: 0.2
    5:
      dc_voltage: null
      pump_frequency: 10.25
      pump_amplitude: null
    6:
      dc_voltage: 0.5135416666666667
      pump_frequency: 10.25
      pump_amplitude: 0.22
      # dc_voltage: 0.5215
      # pump_frequency: 10.5
      # pump_amplitude: 0.31
      # dc_voltage: 0.484
      # pump_frequency: 10.479167
      # pump_amplitude: 0.34
    7:
      dc_voltage: null
      pump_frequency: 10.25
      pump_amplitude: null
    8:
      dc_voltage: 1.602
      pump_frequency: 10.35
      pump_amplitude: 0.17
    9:
      dc_voltage: 0.2535
      pump_frequency: 10.25
      pump_amplitude: 0.1275
    10:
      dc_voltage: null
      pump_frequency: 10.25
      pump_amplitude: null
    11:
      dc_voltage: null
      pump_frequency: 10.25
      pump_amplitude: null
    12:
      dc_voltage: 0.1883
      pump_frequency: 10.0625
      pump_amplitude: 0.0375
    13:
      dc_voltage: null
      pump_frequency: 10.25
      pump_amplitude: null
    14:
      dc_voltage: null
      pump_frequency: 10.25
      pump_amplitude: null
    15:
      dc_voltage: 0.197
      pump_frequency: 10.37
      pump_amplitude: 0.22
